// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{
    type: 'autogenerated',
    dirName: '.'
  }, {
    type: 'link',
    label: 'Toolset Download',
    href: 'https://github.com/GaijinEntertainment/GaijinApplicationPlatform/releases',
  }],
};

module.exports = sidebars;
